# .github/release.yml

changelog:
    categories:
        - title: New features 🎉
          labels:
              - enhancement
        - title: Bugs fixed 🛠
          labels:
              - bug

        - title: Other Changes
          labels:
              - '*'
