name: Build and Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Release version number'
                required: true

jobs:
    build-and-release:
        runs-on: ubuntu-latest
        environment: production
        permissions:
            contents: write
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            # - name: Setup Node
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: 18

            - name: Update manifest.json
              run: |
                  sed -i.bak "s/\"version\": \".*\"/\"version\": \"$GITHUB_ACTION_VERSION\"/" src/manifest.json && rm src/manifest.json.bak
              env:
                  GITHUB_ACTION_VERSION: ${{ github.event.inputs.version }}

            - name: Install dependencies
              run: |
                  npm install

            - name: Set environment variable
              run: |
                  echo "NODE_ENV=production" >> $GITHUB_ENV

            - name: Load environment variables
              run: |
                  echo API_SERVER=${{ vars.API_SERVER }} >> .env.production
                  echo API_KEY=${{ vars.API_KEY }} >> .env.production
                  echo AMPLITUDE_KEY=${{ vars.AMPLITUDE_KEY }} >> .env.production

            - name: Build
              run: |
                  npm run build

            - name: Compress build artifacts
              uses: montudor/action-zip@v1
              with:
                  args: zip -qq -r blockfence-${{ github.event.inputs.version }}.zip build/

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: blockfence-${{ github.event.inputs.version }}.zip
                  name: ${{ github.event.inputs.version }}
                  tag_name: ${{ github.event.inputs.version }}
                  generate_release_notes: true
                  prerelease: true
