name: Build Internal

on:
    [push]
        
jobs:
    build-internal:
        runs-on: ubuntu-latest
        environment: staging
        permissions:
            contents: write
            security-events: write
            actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Update manifest.json
              run: |
                  sed -i.bak "s/\"version\": \".*\"/\"version\": \"$GITHUB_ACTION_VERSION\"/" src/manifest.json && rm src/manifest.json.bak
              env:
                  GITHUB_ACTION_VERSION: "0.0.0"

            - name: Install dependencies
              run: |
                  npm install

            - name: Set environment variable
              run: |
                  echo "NODE_ENV=production" >> $GITHUB_ENV

            - name: Load environment variables
              run: |
                  echo API_SERVER=${{ vars.API_SERVER_LATEST }} >> .env.production
                  echo API_KEY=${{ vars.API_KEY }} >> .env.production
                  echo AMPLITUDE_KEY=${{ vars.AMPLITUDE_KEY }} >> .env.production

            - name: Build
              run: |
                  npm run build

            - name: Compress build artifacts
              run: |
                  cd build
                  echo ${{ github.sha }}
                  zip -qq -r ../blockfence-${{ github.sha }}-internal.zip *
                  cd ..

            - uses: actions/upload-artifact@v3
              with:
                name: internal-build
                path: blockfence-${{ github.sha }}-internal.zip

            - name: notify slack
              id: slack
              uses: slackapi/slack-github-action@v1.23.0
              env:
                SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
